<a href="https://colab.research.google.com/github/ngozanlouisano/atom-script/blob/master/ann_breast_cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
# installation des paquer
from sklearn import datasets
import numpy as np 
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split


In [5]:
# Telecharger la base de données
df = datasets.load_breast_cancer()

In [6]:
# Decouvrir la base de données 
print(df.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [7]:
df.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [8]:
df.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [9]:
from re import X
# préparer les données 
X = df.data
y= df.target

In [10]:
scaler=StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [11]:
# separer les données de tests et les données d'entrainements
X_train, X_test, y_train , y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [12]:
print(X_train.shape, X_test.shape)

(455, 30) (114, 30)


In [13]:
# Construction de réseau de neurone 
  # Création du réseau de neurone
model = tf.keras.models.Sequential()

In [14]:
# Ajouter la première couche caché
model.add(tf.keras.layers.Dense(units=15, activation='relu', kernel_initializer='uniform', input_dim=30))

In [15]:
# specifier la couche de sortie
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid', kernel_initializer='uniform'))

In [16]:
# précuser la fonction cout / pour mettre à jour les poids 
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['binary_accuracy'])

In [17]:
# une synthèse de ce qu'on a construire 
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 15)                465       
                                                                 
 dense_1 (Dense)             (None, 1)                 16        
                                                                 
Total params: 481
Trainable params: 481
Non-trainable params: 0
_________________________________________________________________


In [18]:
# Entrainer notre réseau de neurone 
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
15/15 [==============================] - 1s 3ms/step - loss: 0.6819 - binary_accuracy: 0.9231
Epoch 2/100
15/15 [==============================] - 0s 3ms/step - loss: 0.6481 - binary_accuracy: 0.9297
Epoch 3/100
15/15 [==============================] - 0s 3ms/step - loss: 0.5917 - binary_accuracy: 0.9209
Epoch 4/100
15/15 [==============================] - 0s 2ms/step - loss: 0.5162 - binary_accuracy: 0.9187
Epoch 5/100
15/15 [==============================] - 0s 2ms/step - loss: 0.4330 - binary_accuracy: 0.9275
Epoch 6/100
15/15 [==============================] - 0s 2ms/step - loss: 0.3589 - binary_accuracy: 0.9407
Epoch 7/100
15/15 [==============================] - 0s 2ms/step - loss: 0.2991 - binary_accuracy: 0.9495
Epoch 8/100
15/15 [==============================] - 0s 2ms/step - loss: 0.2542 - binary_accuracy: 0.9538
Epoch 9/100
15/15 [==============================] - 0s 3ms/step - loss: 0.2221 - binary_accuracy: 0.9582
Epoch 10/100
15/15 [==========================

In [19]:
# Pour tester notre modèle
test_accuracy, test_loss = model.evaluate(X_test, y_test)
print(f"Test accuracy {test_accuracy}  et Test loss {test_loss}" )

4/4 [==============================] - 0s 4ms/step - loss: 0.0518 - binary_accuracy: 0.9825
Test accuracy 0.05184190347790718  et Test loss 0.9824561476707458
