<a href="https://colab.research.google.com/github/ngozanlouisano/atom-script/blob/master/Numpy_TP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importer Numpy
import numpy as np

# 10 Array / un Tableau
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [2]:
# Linspace / cette fonction renvoie donc un array qui contient des valeur décimales exprimé en float
np.linspace(0,50,51)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [5]:
# Arange / cette fonction nous renvoies uniquement des entiers 
np.arange(0,50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [7]:
# 2D array / Tableau 2 Dimension
arr_bis = np.array([[1,2,3], [4,5,6],[7,8,9]])
arr_bis


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Matrice nulle
nul = np.zeros([3,5])
nul

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
# Matrice identité / est une matrice remplie de Zéros uniquement sur la diagonale la valeur aligné
I = np.identity(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
# Matrice unité
One = np.ones([5,5])
One

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# Adittion de deux matrices 
I + One

array([[2., 1., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 1., 2., 1., 1.],
       [1., 1., 1., 2., 1.],
       [1., 1., 1., 1., 2.]])

In [16]:
# Soustrait deux ùatrices 
I - One

array([[ 0., -1., -1., -1., -1.],
       [-1.,  0., -1., -1., -1.],
       [-1., -1.,  0., -1., -1.],
       [-1., -1., -1.,  0., -1.],
       [-1., -1., -1., -1.,  0.]])

In [17]:
# Multiplication Scalaire 
I * 15

array([[15.,  0.,  0.,  0.,  0.],
       [ 0., 15.,  0.,  0.,  0.],
       [ 0.,  0., 15.,  0.,  0.],
       [ 0.,  0.,  0., 15.,  0.],
       [ 0.,  0.,  0.,  0., 15.]])

**Random**

In [28]:
# Tableau 1D aléatoire dans les valeurs 0 et 1
ran = np.random.rand(6)
ran

array([0.47753644, 0.88132684, 0.41954406, 0.38182312, 0.13169499,
       0.88399745])

In [29]:
# Comment trouver la forme d’un tableau et transformer un tableau 1D en tableau 2D
print(f"Tableau = {np.shape(ran)}")

# Reshape
ran = ran.reshape(-1,1)

# New shape
print(f"Tableau = {np.shape(ran)}")

Tableau = (6,)
Tableau = (6, 1)


In [30]:
# Random integer value /génerer des variable aléatoire sans suivre une loi de probalité précise 
arr_int = np.random.randint(100, size=(5,5))
arr_int

array([[46, 98, 69, 98, 41],
       [17, 22, 58, 20, 11],
       [69, 64, 84, 15,  1],
       [24, 95, 88, 47, 29],
       [56, 71, 87, 64, 75]])

In [32]:
# Normal 1 Dim
normal = np.random.normal(loc=0, scale=1, size=(6,))
normal

array([-1.59559372, -0.30871223,  0.67865947, -0.98701771, -0.44604647,
       -1.26324948])

In [33]:
# Normal 2 Dim
normal = np.random.normal(loc=0, scale=1, size=(6,6))
normal

array([[ 0.87167309,  0.05367165, -1.22946584,  0.54797237, -2.08400306,
         0.34145585],
       [-0.53653444, -1.03876743,  0.11602886, -1.71220838,  0.30844631,
        -2.48294976],
       [ 0.87546764, -0.66211963, -1.18138501,  1.43652051,  2.13417254,
        -1.22425771],
       [-0.29164883, -1.42663658,  0.43768316,  0.59453761, -0.45616906,
         1.02492361],
       [-0.61645325,  1.12902143,  0.26904046, -0.85115545,  0.06954604,
         0.62444046],
       [ 0.5873832 , -0.89716729, -0.62642903,  0.65751533,  0.37099118,
        -0.78496897]])

In [35]:
# Set the seed / la graine aléatoire 
print(np.random.rand(3))
print(np.random.rand(3))

np.random.seed(seed=32)
print(np.random.rand(3))

np.random.seed(seed=32)
print(np.random.rand(3))

[0.95565655 0.7366696  0.81620514]
[0.10108656 0.92848807 0.60910917]
[0.85888927 0.37271115 0.55512878]
[0.85888927 0.37271115 0.55512878]


**Indexing Slicing Transformations**

In [47]:
# Choisissez une valeur dans la matrice / extrait des chiffres dans notre matice
arr_bis = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
arr_bis[0][0]

1

In [46]:
arr_bis[0,0]

1

In [49]:
print(arr_bis[1,2])
print(arr_bis[2,2])

6
9


In [54]:
# Choisissez la sous-matrice dans la matrice
arr_bis[0:2, 0:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
# Choisissez une colonne ou une ligne
print(arr_bis[1,:]) # extrait une ligne
print(arr_bis[:,2]) # extrait une column

[4 5 6]
[3 6 9]


In [63]:
# Maximun de la matrice arr_bis 
# One the matrix
print(arr_bis.max())

# Maximun par rapport au Ligne
print(arr_bis.max(axis=1))

# Maximun par rapport au Column
print(arr_bis.max(axis=0))

9
[3 6 9]
[7 8 9]


In [64]:
# Minimun de la matrice arr_bis 
# One the matrix
print(arr_bis.min())

# Minimun par rapport au Ligne
print(arr_bis.min(axis=1))

# Minimun par rapport au Column
print(arr_bis.min(axis=0))

1
[1 4 7]
[1 2 3]


In [65]:
# Moyenne de la matrice arr_bis 
# One the matrix
print(arr_bis.mean())

# Moyenne par rapport au Ligne
print(arr_bis.mean(axis=1))

# Moyenne par rapport au Column
print(arr_bis.mean(axis=0))

5.0
[2. 5. 8.]
[4. 5. 6.]


In [66]:
# Ecart-type de la matrice arr_bis 
# One the matrix
print(arr_bis.std())

# Ecart-type par rapport au Ligne
print(arr_bis.std(axis=1))

# Ecart-type par rapport au Column
print(arr_bis.std(axis=0))

2.581988897471611
[0.81649658 0.81649658 0.81649658]
[2.44948974 2.44948974 2.44948974]


In [70]:
# Autre moyen disponible / pour calculer en un coût
print(np.max(arr_bis, axis=0)) # Maximun
print(np.min(arr_bis, axis=0)) # Minimun
print(np.mean(arr_bis, axis=0)) # Moyenne 
print(np.std(arr_bis, axis=0))  # Ecart-type

[7 8 9]
[1 2 3]
[4. 5. 6.]
[2.44948974 2.44948974 2.44948974]


In [72]:
# Logaritm fonction / cette fonction est definie uniquement pour les chiffre positif
np.log(arr_bis)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [73]:
# Exponential fonction / est l'inverse de la fonction logarithm
np.exp(np.log(arr_bis))


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [74]:
# Square fonction / fonction carrée
np.sqrt(arr_bis)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [76]:
# Concatenate (assemblé des  matrices)
# Params : tuple des tableaux et l’axe de la concatenantion
# Concat 1 dimension
arr1 = arr_bis[:,1]
arr2  = arr_bis[:,2]

print(f"ARR1 {arr1}")
print(f"ARR2 {arr2}")

print(np.concatenate((arr1, arr2), axis=0)) # concatenation de deux matrix



ARR1 [2 5 8]
ARR2 [3 6 9]
[2 5 8 3 6 9]


In [79]:
# Concatenation 2 dimension 
arr1 = arr1.reshape(-1,1)
arr2  = arr2.reshape(-1,1)

print(f"ARR1 {arr1}")
print(f"ARR2 {arr2}")

print(np.concatenate((arr1, arr2), axis=0)) # concatenation de deux matrix

ARR1 [[2]
 [5]
 [8]]
ARR2 [[3]
 [6]
 [9]]
[[2]
 [5]
 [8]
 [3]
 [6]
 [9]]


In [80]:
# Concat 2 dimension 
print(np.concatenate((arr1, arr2), axis=1)) # concatenation de deux matrix

[[2 3]
 [5 6]
 [8 9]]
